-- sql three
-- listing all managers with details
SELECT 
E.EMP_NO, 
E.LAST_NAME, 
E.FIRST_NAME, 
DM.DEPT_NO, DS.DEPT_NAME, DM.FROM_DATE, DM.TO_DATE FROM EMPLOYEES E
JOIN DEPT_MANAGER DM
	ON DM.EMP_NO = E.EMP_NO
JOIN DEPARTMENTS DS
	ON DM.DEPT_NO = DS.DEPT_NO
ORDER BY E.LAST_NAME