-- sql six 
-- listing sales department employees
SELECT 
E.EMP_NO, 
E.LAST_NAME, 
E.FIRST_NAME, 
DS.DEPT_NAME 
FROM EMPLOYEES AS E
JOIN DEPT_EMP AS DE
	ON E.EMP_NO = DE.EMP_NO
JOIN DEPARTMENTS DS
	ON DE.DEPT_NO = DS.DEPT_NO
WHERE DS.DEPT_NAME = 'Sales'
ORDER BY E.LAST_NAME ASC;
